export const EventTypes = {
  MENU_OPENED: 'MENU_OPENED',
  CATEGORY_VIEWED: 'CATEGORY_VIEWED',
  CATEGORY_ATTENTION: 'CATEGORY_ATTENTION',
  CATEGORY_NAV_TAP: 'CATEGORY_NAV_TAP',
  DISH_VIEWED: 'DISH_VIEWED',
  DISH_ATTENTION: 'DISH_ATTENTION',
  SEARCH_PERFORMED: 'SEARCH_PERFORMED',
  ZERO_RESULT_SEARCH: 'ZERO_RESULT_SEARCH',
  SEARCH_RECOVERY_CLICKED: 'SEARCH_RECOVERY_CLICKED',
  FILTER_APPLIED: 'FILTER_APPLIED',
  FILTER_CLEARED: 'FILTER_CLEARED',
  DISH_INFO_VIEWED: 'DISH_INFO_VIEWED',
  DISH_COMPARISON: 'DISH_COMPARISON',
  DISH_COMPARED: 'DISH_COMPARED',
  COMPARISON_COMPLETED: 'COMPARISON_COMPLETED',
  DISH_SELECTED: 'DISH_SELECTED',
  MENU_EXITED: 'MENU_EXITED',
  PREFERENCE_SELECTED: 'PREFERENCE_SELECTED',
  HELP_ME_CHOOSE_STARTED: 'HELP_ME_CHOOSE_STARTED',
  HELP_ME_CHOOSE_COMPLETED: 'HELP_ME_CHOOSE_COMPLETED',
  ASSISTANT_OPENED: 'ASSISTANT_OPENED',
  ASSISTANT_QUESTION_ASKED: 'ASSISTANT_QUESTION_ASKED',
  ASSISTANT_RECOMMENDATION_CLICKED: 'ASSISTANT_RECOMMENDATION_CLICKED',
  SHORTLIST_ITEM_ADDED: 'SHORTLIST_ITEM_ADDED',
  SHORTLIST_ITEM_REMOVED: 'SHORTLIST_ITEM_REMOVED',
  SHORTLIST_VIEWED: 'SHORTLIST_VIEWED',
  INGREDIENT_TAPPED: 'INGREDIENT_TAPPED',
};

export const EVENT_TYPE_LIST = Object.values(EventTypes);

export const ATTENTION_EVENT_TYPES = new Set([
  EventTypes.CATEGORY_ATTENTION,
  EventTypes.DISH_ATTENTION,
]);

/** Minimum dwell (ms) before an attention segment is worth recording. */
export const MIN_ATTENTION_MS = 1000;

/** Minimum visible time (ms) before a dish/card impression is recorded. */
export const MIN_VIEW_MS = 500;

/** Visibility ratio considered "meaningful". */
export const MEANINGFUL_VISIBILITY_RATIO = 0.45;
