-- AlterTable
ALTER TABLE "Restaurant" ADD COLUMN "gstEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Restaurant" ADD COLUMN "gstin" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN "cgstRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Restaurant" ADD COLUMN "sgstRate" DECIMAL(5,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN "cgstRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "sgstRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "cgstAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "sgstAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "taxAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;
